# Generated by Django 3.1.3 on 2020-11-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201115_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_teamadmin',
            field=models.BooleanField(default=False),
        ),
    ]
