# Generated by Django 3.1.3 on 2020-11-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201115_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_packup',
        ),
        migrations.AddField(
            model_name='availability',
            name='is_packup',
            field=models.BooleanField(default=False),
        ),
    ]
